version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 9999:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: posgres
